#!/bin/bash
# c4a logging wrapper
# Usage: c4a_script_logging <level> <message...>

log_event_c4a() {
  local level="$1"; shift || true
  local msg="$*"
  # Default to notice if level missing
  if [[ -z "$level" ]]; then
    level="notice"
  fi
  case "$level" in
    debug|DEBUG)
      logger -p user.debug -t c4a -- "$msg" ;;
    info|INFO)
      logger -p user.info -t c4a -- "$msg" ;;
    notice|NOTICE)
      logger -p user.notice -t c4a -- "$msg" ;;
    warn|warning|WARN|WARNING)
      logger -p user.warning -t c4a -- "$msg" ;;
    err|error|ERR|ERROR)
      logger -p user.err -t c4a -- "$msg" ;;
    crit|CRIT)
      logger -p user.crit -t c4a -- "$msg" ;;
    alert|ALERT)
      logger -p user.alert -t c4a -- "$msg" ;;
    emr|emerg|emergency|EMERG)
      logger -p user.emerg -t c4a -- "$msg" ;;
    *)
      logger -p user.notice -t c4a -- "Invalid log level '$level'. $msg" ;;
  esac
}

log_event_c4a "$@"

